### ISSUE TITLE
How to install!

### ISSUE THREAD

**Issue by DarkShihodo** [danwillm/VRCFT-SteamLink#1]
Hey sorry, dumb dumb here, been at it for a hour to figure out just how to even install the modules, would appriciate you showing me how dumb I am atm lol.

**Comment by ykeara** [comment]
Going to jump in here and speak for Dan a bit.
Dan's module is intended and designed to be mainly an example solution for steamlink. more so as developer documentation than end user use cases.

That being said for now  you can download the "release" [https://github.com/danwillm/VRCFT-SteamLink/releases/latest](https://github.com/danwillm/VRCFT-SteamLink/releases/latest) from that link, [specifically the zip file] and in VRCFT simply click install module from zip, and that should be all you need to do.

in general i would look at [VRCFT's documentation](https://docs.vrcft.io/docs/hardware/quest-pro#steamlink-setup) for additional setup though.
